name: Cache store restore
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize"]
jobs:
  showinfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables
      - name: show info
        run: echo "This job at $GITHUB_RUN_ID $GITHUB_JOB"
  # Cache: https://github.com/actions/cache
  job_store_cache_in_workflow:
    needs: showinfo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: store cache
        id: cache-dist
        uses: actions/cache@v3
        env:
          cache-name: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}
      - name: Generate file
        run: |
          make generate
          make log VALUE=$GITHUB_RUN_ID-$GITHUB_HEAD_REF-$GITHUB_JOB-$GITHUB_EVENT_NAME
      - name: show current working directory
        run: |
          pwd
          ls -la

  job_restore_cache_in_workflow:
    needs: job_store_cache_in_workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: restore cache
        id: cache-dist
        uses: actions/cache@v3
        env:
          cache-name: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}
      - name: show current working directory
        run: |
          pwd
          ls -la
      - name: check cache file
        run: |
          make check
          make show-log
