name: Release PR

on:
  workflow_dispatch

jobs:
  make_release_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: remove rc
        run: sed -i -e 's/-rc//g' VERSION
      - name: get version
        id: current-version
        run: echo "VERSION=" | cat -v - VERSION | sed -z 's/[ \n]//g' >> $GITHUB_OUTPUT
      
      - name: show version
        run: echo update to {{steps.current-version.outputs.VERSION}}

      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.github_token }}
      #     commit-message: Release
