name: Auto release tag

on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize"]
  

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get version
        id: current-version
        run: echo "VERSION=" | cat -v - VERSION | sed -z 's/[ \n]//g' >> $GITHUB_OUTPUT
      - name: check version
        id: check-version
        continue-on-error: true
        run: |
          sed -E 's/-.*//g' VERSION > FILDERED_VERSION
          diff VERSION FILDERED_VERSION
      - name: Error handling
        if: ${{ steps.check-version.outcome == 'failure' }}
        run: |
          echo "Error handling"
          echo ${{ steps.error_execution.outcome }}
      
      - name: set tag
        run: git tag -a v${{steps.current-version.outputs.VERSION}} -m "release ${{steps.current-version.outputs.VERSION}}"

