name: Cache store restore
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize"]
jobs:
  showinfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables
      - name: check secrets
        env:
          AAA: ${{ secrets.AAA }}
        run: |
          echo "$AAA"
