name: Use secrets
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize"]
jobs:
  check-secrets:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
      - name: check secrets
        env:
          AAA: ${{ secrets.AAA }}
          BBB: ${{ secrets.BBB }}
          SEC: ${{ secrets.SEC }}
        run: |
          echo aaa is $AAA
          echo bbb is $BBB
          echo sec is $SEC
          echo $SEC > sec.txt
          cat sec.txt