name: Use secrets
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize"]
jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables
      - name: check secrets
        env:
          AAA: ${{ secrets.AAA }}
          SEC: ${{ secrets.SEC }}
        run: |
          echo aaa is $AAA
          echo sec is $SEC
          echo $SEC > sec.txt
          cat sec.txt